// <auto-generated />
namespace AKP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class validationAd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validationAd));
        
        string IMigrationMetadata.Id
        {
            get { return "201703062036196_validation Ad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
